// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RouteTimer.Persistence;

#nullable disable

namespace RouteTimer.Persistence.Migrations
{
    [DbContext(typeof(RouteTimerDbContext))]
    [Migration("20260830053433_AddPredictionAdjustments")]
    partial class AddPredictionAdjustments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RouteTimer.Persistence.Entities.ActivitySampleEntity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<byte?>("Cadence")
                        .HasColumnType("smallint");

                    b.Property<bool>("CrossesDiscontinuity")
                        .HasColumnType("boolean");

                    b.Property<double>("CurvaturePerMetre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<double>("ElevationMetres")
                        .HasColumnType("double precision");

                    b.Property<double>("Gradient")
                        .HasColumnType("double precision");

                    b.Property<byte?>("HeartRate")
                        .HasColumnType("smallint");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("MovingElapsedSeconds")
                        .HasColumnType("double precision");

                    b.Property<int?>("PowerWatts")
                        .HasColumnType("integer");

                    b.Property<double>("SpeedMetresPerSecond")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActivityId", "Sequence");

                    b.ToTable("activity_samples", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.AnalysisJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiagnosticCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DiagnosticMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("ProgressStage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("State", "LeaseExpiresAt", "CreatedAt");

                    b.HasIndex(new[] { "Type", "SubjectId" }, "IX_analysis_jobs_queued_type_subject")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Queued'");

                    b.HasIndex(new[] { "Type", "SubjectId" }, "IX_analysis_jobs_running_type_subject")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Running'");

                    b.ToTable("analysis_jobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_analysis_jobs_progress", "\"ProgressPercent\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.GarminActivityImportEntity", b =>
                {
                    b.Property<string>("GarminActivityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.HasKey("GarminActivityId");

                    b.HasIndex("UploadId");

                    b.ToTable("garmin_activity_imports", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.GarminConnectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("EncryptionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("GarminUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("garmin_connections", null, t =>
                        {
                            t.HasCheckConstraint("CK_garmin_connections_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.GoogleMapsCredentialEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("EncryptionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("KeyHint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("google_maps_credentials", null, t =>
                        {
                            t.HasCheckConstraint("CK_google_maps_credentials_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.LocalCredentialEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("local_credential", null, t =>
                        {
                            t.HasCheckConstraint("CK_local_credential_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PowerBandEntity", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DurationKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ActivityCount")
                        .HasColumnType("integer");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("EvidenceSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("ShrinkageWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("TypicalWatts")
                        .HasColumnType("double precision");

                    b.HasKey("ModelId", "GradeKey", "DurationKey");

                    b.ToTable("power_bands", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionAdjustmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AveragePowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSpeedMetresPerSecond")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Confidence")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MovingSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StrategyAlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StrategyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("PredictionId", "CreatedAt");

                    b.ToTable("prediction_adjustments", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionAdjustmentSegmentEntity", b =>
                {
                    b.Property<Guid>("AdjustmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("CumulativeMovingSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double>("SegmentMovingSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedMetresPerSecond")
                        .HasColumnType("double precision");

                    b.Property<string>("StrategyPhase")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("WPrimeBalanceJoules")
                        .HasColumnType("double precision");

                    b.Property<int?>("ZoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("AdjustmentId", "Sequence");

                    b.ToTable("prediction_adjustment_segments", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AscentMetres")
                        .HasColumnType("double precision");

                    b.Property<bool>("AssumptionMovingOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("AssumptionSurface")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssumptionWeather")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AssumptionWind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("AveragePowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSpeedMetresPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double>("BikeWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Confidence")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DistanceMetres")
                        .HasColumnType("double precision");

                    b.Property<long?>("GarminCourseId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("GarminCourseUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ModelValidationMedianApe")
                        .HasColumnType("double precision");

                    b.Property<double?>("ModelValidationP90Ape")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("ModelWasCalibrated")
                        .HasColumnType("boolean");

                    b.Property<double?>("MovingSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RiderModelId")
                        .HasColumnType("uuid");

                    b.Property<double>("RiderWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RiderModelId");

                    b.HasIndex("UploadId");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionSegmentEntity", b =>
                {
                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("CumulativeDistanceMetres")
                        .HasColumnType("double precision");

                    b.Property<double>("CumulativeMovingSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("CurvaturePerMetre")
                        .HasColumnType("double precision");

                    b.Property<double>("ElevationMetres")
                        .HasColumnType("double precision");

                    b.Property<double>("Gradient")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("PredictedPowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double>("PredictedSpeedMetresPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double>("SegmentDistanceMetres")
                        .HasColumnType("double precision");

                    b.Property<double>("SegmentMovingSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("PredictionId", "Sequence");

                    b.ToTable("prediction_segments", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.RiderModelDescentLimitEntity", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CurvatureKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ActivityCount")
                        .HasColumnType("integer");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("EvidenceSeconds")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("boolean");

                    b.Property<double>("SpeedCapMetresPerSecond")
                        .HasColumnType("double precision");

                    b.HasKey("ModelId", "GradeKey", "CurvatureKey");

                    b.ToTable("rider_model_descent_limits", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.RiderModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AirDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("CdA")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Crr")
                        .HasColumnType("double precision");

                    b.Property<bool>("DescentWasLearned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<double>("DrivetrainEfficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("GlobalTypicalWatts")
                        .HasColumnType("double precision");

                    b.Property<double>("ProfileBikeWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double>("ProfileRiderWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValidationMedianApe")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValidationP90Ape")
                        .HasColumnType("double precision");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("WasCalibrated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("rider_models", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.RiderProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BikeAndEquipmentWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double>("RiderWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("rider_profile", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.StoredUploadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Sha256")
                        .IsUnique();

                    b.ToTable("stored_uploads", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.TrainingActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AscentMetres")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceManufacturer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceProduct")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("DistanceMetres")
                        .HasColumnType("double precision");

                    b.Property<double>("ElevationCoverage")
                        .HasColumnType("double precision");

                    b.Property<string>("Eligibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExclusionCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("MovingDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("PositionCoverage")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerCoverage")
                        .HasColumnType("double precision");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("SpeedCoverage")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadId");

                    b.ToTable("training_activities", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.ActivitySampleEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.TrainingActivityEntity", null)
                        .WithMany("Samples")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.GarminActivityImportEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.StoredUploadEntity", null)
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PowerBandEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.RiderModelEntity", null)
                        .WithMany("Bands")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionAdjustmentEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.PredictionEntity", null)
                        .WithMany()
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionAdjustmentSegmentEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.PredictionAdjustmentEntity", null)
                        .WithMany("Segments")
                        .HasForeignKey("AdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.RiderModelEntity", "RiderModel")
                        .WithMany()
                        .HasForeignKey("RiderModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RouteTimer.Persistence.Entities.StoredUploadEntity", "Upload")
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RiderModel");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionSegmentEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.PredictionEntity", null)
                        .WithMany("Segments")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.RiderModelDescentLimitEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.RiderModelEntity", "Model")
                        .WithMany("DescentLimits")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionAdjustmentEntity", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionEntity", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.RiderModelEntity", b =>
                {
                    b.Navigation("Bands");

                    b.Navigation("DescentLimits");
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.TrainingActivityEntity", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
