// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RouteTimer.Persistence;

#nullable disable

namespace RouteTimer.Persistence.Migrations
{
    [DbContext(typeof(RouteTimerDbContext))]
    [Migration("20260824121055_AddRiderModels")]
    partial class AddRiderModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RouteTimer.Persistence.Entities.ActivitySampleEntity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<byte?>("Cadence")
                        .HasColumnType("smallint");

                    b.Property<bool>("CrossesDiscontinuity")
                        .HasColumnType("boolean");

                    b.Property<double>("ElevationMetres")
                        .HasColumnType("double precision");

                    b.Property<double>("Gradient")
                        .HasColumnType("double precision");

                    b.Property<byte?>("HeartRate")
                        .HasColumnType("smallint");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("MovingElapsedSeconds")
                        .HasColumnType("double precision");

                    b.Property<int?>("PowerWatts")
                        .HasColumnType("integer");

                    b.Property<double>("SpeedMetresPerSecond")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActivityId", "Sequence");

                    b.ToTable("activity_samples", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.AnalysisJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiagnosticCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DiagnosticMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("State", "LeaseExpiresAt", "CreatedAt");

                    b.ToTable("analysis_jobs", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PowerBandEntity", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("GradeKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DurationKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ActivityCount")
                        .HasColumnType("integer");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("EvidenceSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("ShrinkageWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("TypicalWatts")
                        .HasColumnType("double precision");

                    b.HasKey("ModelId", "GradeKey", "DurationKey");

                    b.ToTable("power_bands", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PredictionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BikeWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("RiderWeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("predictions", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.RiderModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AirDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("CdA")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Crr")
                        .HasColumnType("double precision");

                    b.Property<double>("DrivetrainEfficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("GlobalTypicalWatts")
                        .HasColumnType("double precision");

                    b.Property<double>("ProfileBikeWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double>("ProfileRiderWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValidationMedianApe")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValidationP90Ape")
                        .HasColumnType("double precision");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("WasCalibrated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("rider_models", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.RiderProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BikeAndEquipmentWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double>("RiderWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("rider_profile", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.StoredUploadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Sha256")
                        .IsUnique();

                    b.ToTable("stored_uploads", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.TrainingActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ElevationCoverage")
                        .HasColumnType("double precision");

                    b.Property<string>("Eligibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExclusionCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("MovingDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("PositionCoverage")
                        .HasColumnType("double precision");

                    b.Property<double>("PowerCoverage")
                        .HasColumnType("double precision");

                    b.Property<string>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("SpeedCoverage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadId");

                    b.ToTable("training_activities", (string)null);
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.ActivitySampleEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.TrainingActivityEntity", null)
                        .WithMany("Samples")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.PowerBandEntity", b =>
                {
                    b.HasOne("RouteTimer.Persistence.Entities.RiderModelEntity", null)
                        .WithMany("Bands")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.RiderModelEntity", b =>
                {
                    b.Navigation("Bands");
                });

            modelBuilder.Entity("RouteTimer.Persistence.Entities.TrainingActivityEntity", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
